
public interface DimensaoSuperficial { //TUDO QUE ESTA DENTRO DE UMA INTERFACE NAO É REAL, E TUDO QUE ESTÁ AQUI É PUBLICO E ABSTRATO.
	
	double area (); //METODO DENTRO DA INTERFAZE NAO TEM CORPO.

}
